spring:
  application:
    name: simulator
  data:
    mongodb:
      uri: mongodb://localhost:27017/adtech
  datasource:
    url: jdbc:clickhouse://localhost:8123/default
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: ClickHouseHikariPool
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  threads:
    virtual:
      enabled: true

server:
  port: 8080
